### ISSUE TITLE
brain breaks issues

### ISSUE THREAD

**Issue by luzeli29** [luzeli29/iapplymath#125]
A lot of issues with the brain breaks: none are working properly. 

1. The how are you feeling question does not include the emojis and cannot be answered 
2. The free drawing does not include any prompt, timer, or other colors besides red marker
3. pop bubbles is glitchy and I can't actually pop any bubbles, feeling like 3 min might be too long for this
4. the move your body, the mandala, deep breathing, and the chill out break do not work at all.

**Comment by hannahrg2** [comment]
Also, the spanish translations are still in English

**Comment by hannahrg2** [comment]
The deep breathing and move body brain breaks gets interrupted by 
"In progress game found...." and won't let me play the brain break without getting interrupted.

**Comment by Littlegra** [comment]
The bubbles for the brain breaks are irregularly sized? 
![image](https://github.com/luzeli29/iapplymath/assets/137457499/33fe3605-2b4c-459b-9c13-bf416dc764c2)

**Comment by johnleh** [comment]
Issue has been broken to smaller issues...
