### ISSUE TITLE
correct answer sound

### ISSUE THREAD

**Issue by luzeli29** [luzeli29/iapplymath#130]
Can correct answer sound be more enthusiastic like cheering sound?

**Comment by esc20936** [comment]
Solved in PR #134 
![image](https://github.com/luzeli29/iapplymath/assets/77400177/f2e280d0-4bb5-4d5d-8d4d-fb1a2a0fd3fe)

In case you decide to use another cheering sound let me know, in order to change it.
The cheering sound I added is the following:
https://www.youtube.com/watch?v=wovVTW_m9tc

**Comment by esc20936** [comment]
updated sound to a not copy right sound. Did it in PR #151
