### ISSUE TITLE
Level 2 - at 13% 

### ISSUE THREAD

**Issue by kellync3** [luzeli29/iapplymath#139]
![Screenshot 2023-06-20 141526](https://github.com/luzeli29/iapplymath/assets/137215106/1271588c-7373-48e9-829d-047b79734151)

Not sure if the screenshot will show up- the issue is that when you click on the pet, the affirmation doesn't show up as it is covered by the budget sheet.

**Comment by esc20936** [comment]
Solved in PR #162
