### ISSUE TITLE
Decimal only question 

### ISSUE THREAD

**Issue by hannahrg2** [luzeli29/iapplymath#140]
Decimal only question type does not allow whole numbers 

the correct answer was 4

only accepted 4.00 (maybe 4.0 as well)

**Comment by hannahrg2** [comment]
same with whole numbers only questions, 20.00 is considered incorrect when the answer is 20

**Comment by hannahrg2** [comment]
Some questions require whole numbers but the answer is not a whole number 
For example, in one question the formula needed to solve is 22/8. 
also, there is no indication to round for the student.

**Comment by kellync3** [comment]
I encountered the same issue with decimals only. the answer is 100 but it doesn't accept my answer 
![image](https://github.com/luzeli29/iapplymath/assets/137215106/ab399435-a517-46c8-b189-1911d4532c57)

**Comment by kellync3** [comment]
For the above, I was able to move forward by entering 100.00, that was my mistake for not reading properly hehe.

**Comment by esc20936** [comment]
Solve this in PR #172
