### ISSUE TITLE
Seems like images of animals is a little bit too stretched - attaching screenshot 

### ISSUE THREAD

**Issue by gracesonc** [luzeli29/iapplymath#154]
<img width="465" alt="Screen Shot 2023-06-21 at 9 42 12 AM" src="https://github.com/luzeli29/iapplymath/assets/137302388/336cd4c0-812a-4ed8-a1dd-bda684056090">

**Comment by KristenBrandt** [comment]
Fixed

**Comment by KristenBrandt** [comment]
Fixed
