### ISSUE TITLE
Thinking 16pm is a typo? Did you mean 6pm? - "You and Elena arrive at the restaurant at 16pm. If it takes you both 15 minutes to order, at what time will you place the order?"

### ISSUE THREAD

**Issue by gracesonc** [luzeli29/iapplymath#160]

**Comment by esc20936** [comment]
Actually, it is 16, we are using military time.

**Comment by esc20936** [comment]
Fixed in PR #184

**Comment by Littlegra** [comment]
Is the military time format related to content standards? Most grade school kids may not be familiar, unless it's specified in the standards.

**Comment by johnleh** [comment]
After talking to Luz, we will be switching to AM/PM.

**Comment by esc20936** [comment]
Solve in PR #196
