### ISSUE TITLE
Incorrect or confusing question in restaurant scenario

### ISSUE THREAD

**Issue by Littlegra** [luzeli29/iapplymath#182]
![image](https://github.com/luzeli29/iapplymath/assets/137457499/82f5ead9-d6f0-4b15-9e27-57dd2cb07f21)

I typed 1/4 and got "Answer must be a fraction"- but that is the simplified version of 2/8. I think both answers should be accepted here.

**Comment by esc20936** [comment]
This has already been solved in PR #177 , @johnleh, are they using the dev branch or the main branch to test the game?

**Comment by johnleh** [comment]
It has not been pushed to main yet.
