### ISSUE TITLE
game on tablet specifically Ipad (safari)

### ISSUE THREAD

**Issue by kellync3** [luzeli29/iapplymath#191]
when playing the game in Spanish the page with the budget and to select food items is too stretched out that you are unable to see the numbers nor place an order
![Screenshot 2023-06-26 160222](https://github.com/luzeli29/iapplymath/assets/137215106/f661527e-9c44-49c6-846e-b95f20b67af9)

**Comment by johnleh** [comment]
Issue is fixed if you rotate your iPad. At this point, we are not focused on big css changes like this.
