### ISSUE TITLE
Confusing Level 2 question

### ISSUE THREAD

**Issue by pozefsky** [luzeli29/iapplymath#199]
"Roday your parents gave you 10 dollars to order food at the restaurant.  If next time they gave you 2 times less money, what is your new budget?"

2 times less meaning 1/2 is not clear

**Comment by esc20936** [comment]
Fixed in PR #204 
I changed the way the question is phrased.
Instead of saying 2 times less money is gonna say "half of that money"
In case of 3 "a third of that money" and in case is more is gonna say "triple that money"
