### ISSUE TITLE
Level 3 question confusing or broken

### ISSUE THREAD

**Issue by pozefsky** [luzeli29/iapplymath#200]
"If 29/100 is the amount you pay and is represented as .20 in decimal, how would you represent 10/100 of your bill as a decimal"

Tried both .1 and .1 times the bill.  Neither was accepted.

**Comment by esc20936** [comment]
The question is "If 20/100 is the amount you pay and is represented as .20 in decimals, how would you represent 10/100 of your bill as a decimal?"

0.1 is accepted, maybe you didn't type the 0 before the dot?

Also removed the "of your bill" part to be more clear that the question ask to convert the fraction to decimal

@johnleh it's that okay or should we look a way to accept decimals without the 0 before the dot?

**Comment by luzeli29** [comment]
can we please accept .1 as well as 0.1?
