### ISSUE TITLE
Sports Questions - Soccer 

### ISSUE THREAD

**Issue by amt23** [luzeli29/iapplymath#242]
https://docs.google.com/document/d/1a13TOL_v1HkCbSljJ1LQhM0nhJdGzLOc0MB0r0wureY/edit?usp=drive_link

All English levels completed! (12 questions for each level)

Spanish translations are complete

**Comment by esc20936** [comment]
Level 3 is done and commited, so folks would like to pull before working on theirs @KristenBrandt @angelhigueros  @johnleh
