### ISSUE TITLE
issue with level 2 grocery store (no questions)

### ISSUE THREAD

**Issue by luzeli29** [luzeli29/iapplymath#258]
<img width="756" alt="Screen Shot 2023-07-25 at 12 54 24 PM" src="https://github.com/luzeli29/iapplymath/assets/83885083/4444c2fe-221a-48a5-b552-6af81d1f74eb">

**Comment by esc20936** [comment]
So there was an error with the questions generator.

**Comment by esc20936** [comment]
This changes are in the #261 PR
