### ISSUE TITLE
grocery store recipe format needs to be fixed 

### ISSUE THREAD

**Issue by luzeli29** [luzeli29/iapplymath#263]
<img width="549" alt="Screen Shot 2023-07-25 at 7 26 31 PM" src="https://github.com/luzeli29/iapplymath/assets/83885083/f4bcbb6d-4e85-4c78-96c7-3141d7ff235a">
<img width="321" alt="256060682-ca1097ff-40a8-468d-9205-434a93d8496b" src="https://github.com/luzeli29/iapplymath/assets/83885083/81697282-7ebe-473e-8338-c0138d108012">

make sure game recipe matches the document (remove cook time and prep time for all recipes that have it) 
also remove the quantity from the title of the recipe (just include the name of the recipe)
change the servings format - all recipes should have this format "Servings: number" & spanish "Porciones: number"

**Comment by johnleh** [comment]
fixed will be with other bug fixes pushed tonight
